### ISSUE TITLE
Gap between box and holding tray

### ISSUE THREAD

**Issue by Xiondewah** [franpoli/OpenSCADutil#2]
Hi - this is really good and although I'm new to OpenScad I've already started playing about with it.

One thing I'm not clear on - how do I increase the gap between a box and it's supporting tray please?  When these print, they seem to be joined on one side which results in a lot of clean-up.

I'd appreciate your help!

Thanks.

**Comment by franpoli** [comment]
Hi,

Thank you for your comment.

There is a parameter called `tolerance` in the file _ikea_skadis.scad_. You can set this value to your preference to adjust the gap.

If you use the file _ikea_skadis.scad_ as a library, you can override the tolerance value in your new file.

Example:

```scad
/*
 * file skadis_box_demo.scad
 * override tolerance parameter
 */

include <ikea_skadis.scad>

tolerance = 0.9;
skadis_box(90, 40, 30);
```
I have updated the instructions with an [example](https://github.com/franpoli/OpenSCADutil/blob/master/ikea_skadis_pegboard_accessories/ikea_skadis_demo.md#library-usage). I hope this helps.

**Comment by Xiondewah** [comment]
I'd literally just worked that out!  But thank you for your prompt response.  I'm fiddling around with the code and thoroughly enjoying myself :-)

**Comment by Xiondewah** [comment]
One thing I did realise - you don't need the round box section if you just use the fillet and make the length/depth of the square box the same value.

**Comment by Xiondewah** [comment]
I do have a suggestion - on the racks code, add a height value?  It would be good to have a thicker rack for some tools.

If you don't have time, I may be able to work it out myself, but if you do it would be great!

Thanks.

**Comment by franpoli** [comment]
Thank you for your input. I might consider your suggestion on an upcoming iteration. At the moment, you could play with the perimeter and infill settings of your slicer software to increase the strength of your prints.

**Comment by Xiondewah** [comment]
Yes - thanks - already done that and it is better of course.

I've been playing around with the code and have added some embossed text to the front of the box, plate and pliers holder.  It's really helpful to see what you've done as a way to learn OpeScad.  Hellishly complex stuff in there though ;-)
