### ISSUE TITLE
Rounded end to Straight Hook

### ISSUE THREAD

**Issue by stuart264** [franpoli/OpenSCADutil#5]
Really finding this library useful, managed to create just about everything I need but I wanted to ask if there is a way when your using the Straight Hook to create a rounded straight end to the hook that I can specify the diameter of, its for things like my set square and metre metal rule that have rounded holes for hanging?

Stuart.

**Comment by franpoli** [comment]
I apologise for not replying to this message in a timely manner. There may be a way that requires rewriting the code.  I'm closing this issue for the time being, but it is possible that I will consider your idea in a further update.
